language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: simbo/metalsmith-better-excerpts
sudo: false
env:
  global:
    secure: O8JCLLc6v8+eq/o9Qp09TVHie5pVB8x5Kl/mZwTcT7mQOh8cOJFBtvTEAAfWgiJ8SuvvqnvqytX+S4GIa/iqoBZbFkNUk4prXdwtRfc7VLW+d5C9RUIzayifXsIYVRnyvNR3NOnTylgpc3pvKJoxDgi2ZmuqWXErQNmLlaC/GsA=
