language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: ${NPM_API_KEY}
  on:
    tags: true
    repo: simbo/metalsmith-better-excerpts
sudo: false
env:
  global:
  - secure: McfYVxzTxlnRaAkh6uOcaQTe1wZEoV0g3WkmqYxNKC6Cz/JsZZazfl+e+5HX73XnfeIF6ezEWQD3fj0/Cxq8jx73zA5xQsJbOuy3Y0jdzhERHFHKGkU+2lMo/QyI+f7ynQ3xQhzFY0oGRiLqRbyacEiaweaBaSi7eq24ihU6UXs=
